version: '3'
services:
  rabbit:
    hostname: rabbit
    restart: always
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    volumes:
      - /tmp/rabbitmq:/var/lib/rabbitmq
  redis:
    hostname: redis
    restart: always
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    expose:
      - "${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:6379"
  worker:
    hostname: worker
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/worker
    depends_on:
      - rabbit
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbit:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASS}@redis:${REDIS_PORT}/0
  monitor:
    hostname: monitor
    image: mher/flower
    depends_on:
      - rabbit
      - redis
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbit:${RABBITMQ_PORT}
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASS}@redis:${REDIS_PORT}/0
